-- public.acte_medecin definition

-- Drop table

-- DROP TABLE public.acte_medecin;

CREATE TABLE public.acte_medecin (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	acte varchar(255) NULL,
	date_creation timestamp NULL,
	date_last_maj timestamp NULL,
	devise numeric(19, 2) NULL,
	duree int4 NULL,
	prix numeric(19, 2) NULL,
	id_medecin int4 NULL,
	couleur_act varchar(255) NULL,
	flag_actif bool NULL DEFAULT true,
	flag_portail bool NOT NULL DEFAULT false,
	CONSTRAINT acte_medecin_pkey PRIMARY KEY (id)
);


-- public.indisponibilite_medecin definition

-- Drop table

-- DROP TABLE public.indisponibilite_medecin;

CREATE TABLE public.indisponibilite_medecin (
	id_indisponibilite int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_creation timestamp NULL,
	date_debut date NULL,
	date_fin date NULL,
	date_last_maj timestamp NULL,
	heure_debut varchar(255) NULL,
	heure_fin varchar(255) NULL,
	"type" int4 NULL,
	id_medecin int4 NULL,
	CONSTRAINT indisponibilite_medecin_pkey PRIMARY KEY (id_indisponibilite)
);


-- public.medecin definition

-- Drop table

-- DROP TABLE public.medecin;

CREATE TABLE public.medecin (
	id_medecin int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255),
	password varchar(255),
	adresse_cabinet varchar(255) NULL,
	date_debut_convention timestamp NOT NULL,
	date_fin_convention timestamp NULL,
	date_last_maj timestamp NULL,
	etat int4 NOT NULL,
	genre varchar(1) NULL,
	indication varchar(255) NULL,
	nom varchar(255) NULL,
	prenom varchar(255) NULL,
	presentation varchar(1000) NULL,
	id_pays int4 NULL,
	id_region int4 NULL,
	convention_cnam bool NULL,
	code_loc int4 NULL,
	unique_identifiant varchar(255) NULL,
	photo varchar(255) NULL,
	gps_latitude float8 NULL,
	gps_longitude float8 NULL,
	nb_sem_max_planif int2 NULL,
	name_ar varchar(255) NULL,
	prenom_ar varchar(255) NULL,
	presentation_ar varchar(1000) NULL,
	presentation_en varchar(1000) NULL,
	adresse_cabinet_ar varchar(255) NULL,
	adresse_cabinet_en varchar(255) NULL,
	flag_validation_rdv bool NULL,
	flag_inscri_portail bool NOT NULL DEFAULT false,
	flag_inscri_tsm bool NOT NULL DEFAULT false,
	flag_inscri_collect_paiement bool NOT NULL DEFAULT false,
	CONSTRAINT medecin_pkey PRIMARY KEY (id_medecin)
);


-- Add missing columns to medecin table
ALTER TABLE public.medecin 
ADD COLUMN IF NOT EXISTS specialite varchar(255),
ADD COLUMN IF NOT EXISTS qualification varchar(100),
ADD COLUMN IF NOT EXISTS phone_number varchar(50),
ADD COLUMN IF NOT EXISTS date_creation timestamp,
ADD COLUMN IF NOT EXISTS password varchar(255);

-- Update existing doctors with default values if needed
UPDATE public.medecin SET specialite = 'General Practice' WHERE specialite IS NULL;
UPDATE public.medecin SET qualification = 'MBBS' WHERE qualification IS NULL;
-- public.note_patient definition

-- Drop table

-- DROP TABLE public.note_patient;

CREATE TABLE public.note_patient (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_creation timestamp NULL,
	note_medecin varchar(1000) NULL,
	id_medecin int4 NULL,
	id_patient int4 NULL,
	CONSTRAINT note_patient_pkey PRIMARY KEY (id)
);


-- public.patient definition

-- Drop table

-- DROP TABLE public.patient;

CREATE TABLE public.patient (
	id_patient int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_premiere_visite timestamp NULL,
	email varchar(255) NULL,
	genre varchar(1) NULL,
	nom varchar(255) NULL,
	numero_dossier varchar(255) NULL,
	prenom varchar(255) NULL,
	id_famille int4 NULL,
	id_medecin int4 NULL,
	date_naissance date NULL,
	id_telephone_famille int4 NULL,
	adresse_par varchar(255) NULL,
	libelle_convention varchar(255) NULL,
	id_assurance int4 NULL,
	id_convention int4 NULL,
	CONSTRAINT patient_pkey PRIMARY KEY (id_patient)
);


-- public.rdv definition

-- Drop table

-- DROP TABLE public.rdv;

CREATE TABLE public.rdv (
	id_rdv serial4 NOT NULL,
	date_creation timestamp NULL,
	date_last_maj timestamp NULL,
	date_rdv varchar(255) NULL,
	duree int4 NULL,
	etat int4 NULL,
	motif varchar(255) NULL,
	prix_acte numeric(19, 2) NULL,
	id_acte int4 NOT NULL,
	id_medecin int4 NOT NULL,
	id_patient int4 NOT NULL,
	date_supp timestamp NULL,
	id_suppression int4 NULL,
	sms_envoye bool NULL DEFAULT false,
	cause_suppression varchar(255) NULL,
	"source" varchar(255) NULL,
	libelle_convention varchar(255) NULL,
	id_assurance int4 NULL,
	id_convention int4 NULL,
	flag_ancien_patient bool NOT NULL DEFAULT false,
	CONSTRAINT rdv_pkey PRIMARY KEY (id_rdv)
);


-- public.seance_medecin definition

-- Drop table

-- DROP TABLE public.seance_medecin;

CREATE TABLE public.seance_medecin (
	id_seance int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_creation timestamp NULL,
	date_last_maj timestamp NULL,
	debut_indisponibilite time NULL,
	fin_indisponibilite time NULL,
	heure_fermeture time NULL,
	heure_ouverture time NULL,
	jour_semaine int4 NULL,
	regime int4 NULL,
	id_medecin int4 NULL,
	CONSTRAINT seance_medecin_pkey PRIMARY KEY (id_seance)
);


-- public.utilisateur definition

-- Drop table

-- DROP TABLE public.utilisateur;

CREATE TABLE public.utilisateur (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code_pin varchar(255) NULL,
	date_creation timestamp NULL,
	date_last_maj timestamp NULL,
	date_premiere_activation timestamp NULL,
	etat bool NULL,
	flag_gerer_medecin bool NULL,
	flag_gerer_ts bool NULL,
	flag_param bool NULL,
	flag_stats bool NULL,
	login varchar(255) NULL,
	"password" varchar(255) NULL,
	"type" varchar(255) NULL,
	id_assistant int4 NULL,
	id_medecin int4 NULL,
	id_ts int4 NULL,
	id_admin int4 NULL,
	is_demo bool NULL,
	CONSTRAINT uk18vwp4resqussqmlpqnymfqxk UNIQUE (login),
	CONSTRAINT utilisateur_pkey PRIMARY KEY (id)
);



-- missing table creation !
-- Missing tables
CREATE TABLE public.pays (
    id_pays int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    code varchar(10) NULL,
    CONSTRAINT pays_pkey PRIMARY KEY (id_pays)
);

CREATE TABLE public.region (
    id_region int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    id_pays int4 NULL,
    CONSTRAINT region_pkey PRIMARY KEY (id_region)
);

CREATE TABLE public.localite (
    code_loc int4 NOT NULL,
    nom varchar(255) NULL,
    id_region int4 NULL,
    CONSTRAINT localite_pkey PRIMARY KEY (code_loc)
);

CREATE TABLE public.assurance (
    id_assurance int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    CONSTRAINT assurance_pkey PRIMARY KEY (id_assurance)
);

CREATE TABLE public.medecin_convention (
    id_convention int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    libelle varchar(255) NULL,
    CONSTRAINT medecin_convention_pkey PRIMARY KEY (id_convention)
);

CREATE TABLE public.famille (
    id_famille int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    CONSTRAINT famille_pkey PRIMARY KEY (id_famille)
);

CREATE TABLE public.telephone_famille (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    numero varchar(255) NULL,
    CONSTRAINT telephone_famille_pkey PRIMARY KEY (id)
);

CREATE TABLE public.administrateur (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    CONSTRAINT administrateur_pkey PRIMARY KEY (id)
);

CREATE TABLE public.telesecretaire (
    id_telesec int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    CONSTRAINT telesecretaire_pkey PRIMARY KEY (id_telesec)
);

CREATE TABLE public.assistant (
    id_assistant int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NULL,
    CONSTRAINT assistant_pkey PRIMARY KEY (id_assistant)
);



-- public.acte_medecin foreign keys

ALTER TABLE public.acte_medecin ADD CONSTRAINT fkn011iync10k8pcewgyf6ncf9l FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);


-- public.indisponibilite_medecin foreign keys

ALTER TABLE public.indisponibilite_medecin ADD CONSTRAINT fk4to2wmjaef6r1f64tp2tsa6l1 FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);


-- public.medecin foreign keys

ALTER TABLE public.medecin ADD CONSTRAINT fk3ghc5gylmtg5kroewn56mfs1w FOREIGN KEY (id_region) REFERENCES public.region(id_region);
ALTER TABLE public.medecin ADD CONSTRAINT fkjeh1n1j1ttc5smjf3paii0w3b FOREIGN KEY (id_pays) REFERENCES public.pays(id_pays);
ALTER TABLE public.medecin ADD CONSTRAINT fkp4l7l392psunup6a9enb9jyhi FOREIGN KEY (code_loc) REFERENCES public.localite(code_loc);


-- public.note_patient foreign keys

ALTER TABLE public.note_patient ADD CONSTRAINT fk1i4sy96kshyks7vle088u1i71 FOREIGN KEY (id_patient) REFERENCES public.patient(id_patient);
ALTER TABLE public.note_patient ADD CONSTRAINT fkbmet6g1fbof82r8oa4lx8eudx FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);


-- public.patient foreign keys

ALTER TABLE public.patient ADD CONSTRAINT fk6uw4uhic3t2jwprmxdfa25jt7 FOREIGN KEY (id_convention) REFERENCES public.medecin_convention(id_convention);
ALTER TABLE public.patient ADD CONSTRAINT fkc2m90l0v6uy1dgdgknlfngmql FOREIGN KEY (id_telephone_famille) REFERENCES public.telephone_famille(id);
ALTER TABLE public.patient ADD CONSTRAINT fkdonx8d9ec35ls6rofrlbhrist FOREIGN KEY (id_famille) REFERENCES public.famille(id_famille);
ALTER TABLE public.patient ADD CONSTRAINT fkly8x7heqthrcuowo5ot2f80ug FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);
ALTER TABLE public.patient ADD CONSTRAINT fktjp3hs2i5ly287q48qci4ahsj FOREIGN KEY (id_assurance) REFERENCES public.assurance(id_assurance);


-- public.rdv foreign keys

ALTER TABLE public.rdv ADD CONSTRAINT fk8ws1emc2f058yai08y0d3lyq1 FOREIGN KEY (id_acte) REFERENCES public.acte_medecin(id);
ALTER TABLE public.rdv ADD CONSTRAINT fkakybutfcod9kq1bajbi64etmr FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);
ALTER TABLE public.rdv ADD CONSTRAINT fkbw1q4rbeay6pj62ivabauuaun FOREIGN KEY (id_convention) REFERENCES public.medecin_convention(id_convention);
ALTER TABLE public.rdv ADD CONSTRAINT fki5q6kk1p89wd4j79mydxdy0yp FOREIGN KEY (id_assurance) REFERENCES public.assurance(id_assurance);
ALTER TABLE public.rdv ADD CONSTRAINT fkowvey0aimx1in4979u388lvhf FOREIGN KEY (id_patient) REFERENCES public.patient(id_patient);
ALTER TABLE public.rdv ADD CONSTRAINT fkqdho8d41ukph8nfxfj8yii6yn FOREIGN KEY (id_suppression) REFERENCES public.utilisateur(id);


-- public.seance_medecin foreign keys

ALTER TABLE public.seance_medecin ADD CONSTRAINT fk5dnbjtlawpf357lb1447rx9h7 FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);


-- public.utilisateur foreign keys

ALTER TABLE public.utilisateur ADD CONSTRAINT fk5i8g1n0bmyu0giqc0l2vwmw8g FOREIGN KEY (id_admin) REFERENCES public.administrateur(id);
ALTER TABLE public.utilisateur ADD CONSTRAINT fk74se3ucansve13rcquh5r8hpt FOREIGN KEY (id_medecin) REFERENCES public.medecin(id_medecin);
ALTER TABLE public.utilisateur ADD CONSTRAINT fkjjbpd60g0ydkp49adihjlwq2s FOREIGN KEY (id_ts) REFERENCES public.telesecretaire(id_telesec);
ALTER TABLE public.utilisateur ADD CONSTRAINT fkm2bk5nousn4hye9bdlwjpo397 FOREIGN KEY (id_assistant) REFERENCES public.assistant(id_assistant);